### ISSUE TITLE
sorttable.js This document requires 'TrustedScript' assignment

### ISSUE THREAD

**Issue by rumatadest** [backuppc/backuppc#515]
When I click the "Xfer" or "Backup Settings" tab nothing happens.
In debug mode of the browser I see this error.

> This document requires 'TrustedScript' assignment. Navigating to a javascript:-URL is equivalent to a 'TrustedScript' assignment.

and        

> Uncaught TypeError: Failed to set the 'innerHTML' property on 'Element': This document requires 'TrustedHTML' assignment.
     at ts_makeSortable (sorttable.js:43:24)
     at sortables_init (sorttable.js:15:13)

TrustedScript is a new feature from Google Chrome to protect scripts from .js injections.

On the latest version google chrome, the error appears.
On the latest version of firefox everything works fine.

**Comment by GWHAYWOOD** [comment]
In config.pl, maybe you could try adding this to $conf{CgiHeaders}:

```
<script>if (window.trustedTypes && window.trustedTypes.createPolicy) {window.trustedTypes.createPolicy('default', {createHTML: string => string,createScriptURL: string => string,createScript: string => string,});}</script>
```

See for example

https://www.reddit.com/r/GoogleAppsScript/comments/185tw8f/trusted_types_issues/

Please come back to report your experience here.

I confess I have no idea what I'm doing. :)

**Comment by GWHAYWOOD** [comment]
Incidentally here, I don't see this issue on Chromium on my own desktop machine:

Version 126.0.6478.164 (Official Build) Built on Debian , running on Debian 11 (64-bit)

**Comment by GWHAYWOOD** [comment]
No response after a month, closing.
